// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mysmmnlpzdwdebkxguha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15c21tbmxwemR3ZGVia3hndWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Njc2NDcsImV4cCI6MjA2MDE0MzY0N30.6W7Ww4oS1ka9ni-BdOIX0-KPjdM2hqkk75VadTREcSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);